mwildehahn/hack-graphql

- README.md
- src/BaseSchema.hack
- src/Codegen/Generator.hack
- src/Resolver.hack
- src/Types/ObjecType.hack
- src/__Private/Argument.hack
- src/__Private/Variables.hack
- src/playground/Playground.hack
- tests/PlaygroundTest.hack
- tests/gen/Generated.hack
Addresses: https://github.com/mwildehahn/hack-graphql/issues/5
I skipped over validating the arguments just to get this working. I think we'll want to do something [similar to graphpinator](https://github.com/infinityloop-dev/graphpinator/blob/master/src/Graphpinator.php#L69) where they'll "normalize" the request, validating it and any specified arguments against the schema.
I looked at trying to just bring this logic in to get us started but it is a lot of PHP code that is at odds with our generated types.
**Testing**
- Added two test cases, one for variables and one for inline args.
> Initial support for handling inline arguments and variables

- composer.json
- src/Codegen/Generator.hack
- tests/PlaygroundTest.hack
- tests/gen/Generated.hack
Fix for: https://github.com/mwildehahn/hack-graphql/issues/17.
DefinitionFinder supports parsing from a file or path. This lets us move beyond parsing a single file.
We now support generating graphql types for a path:
```
Generator::forPath($path);
```
or a file name:
```
Generator::forFile($path);
```
> Use DefinitionFinder over raw AST

- src/Codegen/Generator.hack
- src/Resolver.hack
- tests/BasicTest.hack
- tests/PlaygroundTest.hack
- tests/gen/Generated.hack
- use DataProvider to avoid some duplicate code
- use base class + separate test class: this allows people to add multiple tests that behave the same way, so we don't get merge conflicts from everyone modifying the same test file
- fix non-deterministic script name
- fix a minor bug, response not following the GraphQL spec (there's an extra `$out['data'][$operation_type]`)
> use DataProvider in PlaygroundTest

- src/Codegen/Generator.hack
- src/Codegen/Types.hack
- src/playground/OutputTypeTestObj.hack
- tests/OutputTypeTest.hack
- tests/PlaygroundTest.hack
- tests/gen/Generated.hack
#29 implemented execution for list/non-nullable fields; this adds the ability to actually codegen fields with such types + a test.
> Support list/nullable field types

- src/Codegen/Generator.hack
- src/Codegen/Types.hack
- src/Field.hack
- src/playground/ErrorTestObj.hack
- tests/ErrorTest.hack
- tests/gen/Generated.hack
Adds codegen support for non-nullable fields (using the new attribute `KillsParentOnException` -- see its docblock for explanation) and a bunch of test cases. The test cases are actually the important part here (I wanted to ensure that error handling is implemented correctly), the support for non-nullable fields is secondary (it was impossible to write the tests without it) and I wouldn't necessarily recommend using them.
That said, non-nullable fields *do* have advantages (mainly, clients don't need as many null checks everywhere, which client developers like a lot), so maybe we shouldn't discourage them as much.
At FB, we heavily discourage non-nullable fields, but that is mostly for historical reasons and not necessarily the right call everywhere.
If you decide that non-nullable fields …
> non-nullable fields + errors

- src/Codegen/Generator.hack
- src/Codegen/Types.hack
- src/InputType.hack
- src/Resolver.hack
- src/Types/Input/InputObjectType.hack
- src/Types/Input/InputType.hack
- src/playground/Playground.hack
- tests/InputTypeTest.hack
- tests/PlaygroundTest.hack
- tests/gen/Generated.hack
Allows tagging of shapes with `<<GraphQL\InputType>>` to support accepting those shapes as input. GraphQL spec: https://graphql.org/learn/schema/#input-types.
> The fields on an input object type can themselves refer to input object types, but you can't mix input and output types in your schema. Input object types also can't have arguments on their fields.
I didn't add any checks for this yet.
One other note, this requires type assertion to verify the incoming dict coerces to the defined type. Not sure if there is a better way to do this.
> Add support for `GraphQL\InputType` attribute

- src/BaseSchema.hack
- src/Codegen/Generator.hack
- src/FieldDefinition.hack
- src/FieldResult.hack
- src/Resolver.hack
- src/Types/Output/LeafType.hack
- src/Types/Output/ListOutputType.hack
- src/Types/Output/NamedOutputType.hack
- src/Types/Output/NullableOutputType.hack
- src/Types/Output/ObjectType.hack
- src/Types/Output/OutputType.hack
- tests/gen/Generated.hack
This makes it possible to more strongly type the 'data' field in `Resolver::TResponse` (statically type-checked, no runtime assertions).
Closes #46
> add generics to FieldResult

- src/Codegen/Generator.hack
- src/Codegen/InputObjectType.hack
- src/Codegen/Types.hack
- src/Types/Input/EnumInputType.hack
- src/Types/Input/InputObjectType.hack
- src/playground/Playground.hack
- tests/InputTypeTest.hack
- tests/gen/Generated.hack
- supports variables nested inside an input object literal (see new test cases)
- supports enum fields (which need to be coerced between const name <-> internal value, which previously wouldn't happen)
- the generated code is type-safe without runtime assertions (TypeAssert), so if we ever introduce a bug into the codegen, Hack should catch it
This doesn't yet handle optional/nullable fields, I'll do those separately tomorrow.
I moved InputObjectType out of Generator.hack since that file was getting very long.
The easiest way to review this is probably look at the changes to the codegen output (Generated.hack) first, the rest should become pretty obvious after that.
> input object coercion

- tests/InputTypeTest.hack
We'll need to be careful to pass darrays instead of dicts into the resolver in HHVM 4.56, at least until we have variable coercion (#44 ) working.
> Fix input object test

- src/Codegen/Generator.hack
- src/Codegen/InputObjectType.hack
- src/Types/Input/InputObjectType.hack
- src/Types/Input/InputType.hack
- src/UserFacingError.hack
- src/playground/Playground.hack
- tests/InputTypeTest.hack
- tests/gen/Generated.hack
The docblock for `hasValue()` and the new test cases are probably the most interesting parts to look at here.
To implement the correct behavior per the GraphQL spec, I had to add the restriction that each field must be both optional and nullable, or neither. If you think this will be too inconvenient, it's probably possible to avoid it, but it will result in some cases that are not covered by the spec where we'll have to decide what to do with them (e.g. if the spec say we should omit a field, where that field is nullable but not optional in Hack, I guess we'd have to put null in there instead of omitting it?).
> support optional input object fields

- src/BaseSchema.hack
- src/Codegen/Generator.hack
- src/Codegen/InputObjectType.hack
- tests/gen/Generated.hack
...so we can use them for introspection, validation, variable coercion, etc.
I made the generics on InputType and OutputType covariant (`+T`) or contravariant (`-T`) as needed. This is so that we can refer to e.g. a list of arbitrary input types as `InputType<mixed>`, which is impossible if the generic type is invariant.
> codegen dicts of input/output types

- src/Codegen/Generator.hack
- src/Codegen/InputObjectType.hack
- src/Codegen/OutputObjectType.hack
- src/Codegen/Types.hack
- src/Types/Output/NamedOutputType.hack
- src/__Private/Attributes/CompositeType.hack
- src/playground/ObjectTypeTestObjects.hack
- tests/ObjectTypeTest.hack
- tests/gen/Generated.hack
Implements much of #53 .
We don't yet support descriptions because we don't yet have a use for them. They'll be used by the introspection system at some point (hopefully soon), and we can revisit then.
The generator code is getting increasingly gnarly. This new `OutputObjectType.hack` `GeneratableClass` looks a lot like both the code for `InputObjectType` and `CompositeObject`. We should find some nice way to share code between these types, but I'm punting for now.
> Support annotating shapes with GraphQL\ObjectType

- src/Codegen/Generator.hack
- src/Codegen/Types.hack
- src/Resolver.hack
- src/Types/Input/EnumInputType.hack
- src/Types/Input/InputObjectType.hack
- src/Types/Input/InputType.hack
- src/Types/Input/ListInputType.hack
- src/Types/Input/NamedInputType.hack
- src/Types/Input/NullableInputType.hack
- tests/BasicTest.hack
- tests/ErrorTest.hack
- tests/InputTypeTest.hack
- tests/gen/Generated.hack
This should get rid of most of the spurious errors from `assertValidVariableValue()`. They may still happen though (until we have query validation), if a variable is used as the value of a field argument of an incompatible type.
Closes #44
> coerce variable values before execution

- src/Graphpinator/Parser/Parser.hack
- src/Graphpinator/Parser/Value/BooleanLiteral.hack
- src/Graphpinator/Parser/Value/FloatLiteral.hack
- src/Graphpinator/Parser/Value/IntLiteral.hack
- src/Graphpinator/Parser/Value/ListVal.hack
- src/Graphpinator/Parser/Value/Literal.hack
- src/Graphpinator/Parser/Value/NullLiteral.hack
- src/Graphpinator/Parser/Value/ObjectVal.hack
- src/Graphpinator/Parser/Value/StringLiteral.hack
- src/Graphpinator/Parser/Value/Value.hack
- src/Types/Input/EnumInputType.hack
- src/Types/Input/NullableInputType.hack
- src/Types/Input/Scalar/BooleanInputType.hack
- src/Types/Input/Scalar/IntInputType.hack
- src/Types/Input/Scalar/StringInputType.hack
- tests/ArgumentTest.hack
- tests/ErrorTest.hack
- tests/Graphpinator/Parser/ParserTest.hack
Adds parser nodes for `IntLiteral`, `StringLiteral` etc. This makes some of the coercion code simpler and safer, and also improves some of our existing error messages (see updated tests).
I removed `getRawValue()` from `Parser\Value` (only `Literal` values have it now). The method would throw if there is a variable reference nested anywhere inside the literal, which is dangerous and would probably surprise anyone who calls it.
> type-safe literals

- .github/workflows/CI.yml
Earlier today I pushed a commit with a typechecker error which didn't cause tests to fail (since the runtime code was alright). We shouldn't allow that.
> Add typechecking to CI

- src/Codegen/Builders/Fields/MethodFieldBuilder.hack
- src/Codegen/Builders/Fields/ShapeFieldBuilder.hack
- src/FieldDefinition.hack
- tests/gen/AnotherObjectShape.hack
- tests/gen/Bot.hack
- tests/gen/Concrete.hack
- tests/gen/ErrorTestObj.hack
- tests/gen/Human.hack
- tests/gen/InterfaceA.hack
- tests/gen/InterfaceB.hack
- tests/gen/IntrospectionTestObject.hack
- tests/gen/Mutation.hack
- tests/gen/ObjectShape.hack
- tests/gen/OutputTypeTestObj.hack
- tests/gen/Query.hack
- tests/gen/Team.hack
- tests/gen/User.hack
- tests/gen/__EnumValue.hack
- tests/gen/__Field.hack
- tests/gen/__InputValue.hack
- tests/gen/__Schema.hack
- tests/gen/__Type.hack
Each field definition should know about its parameters. This will be useful for validation and introspection.
For now, we just generate shapes containing the type, name, and default value for each argument. This might get fancier if we need it to.
> Codegen argument defs

- src/BaseSchema.hack
- src/Graphpinator/Parser/TypeRef/ListTypeRef.hack
- src/Graphpinator/Parser/TypeRef/NamedTypeRef.hack
- src/Graphpinator/Parser/TypeRef/NotNullRef.hack
- src/Graphpinator/Parser/TypeRef/TypeRef.hack
- src/Validation/Rules/KnownArgumentNamesRule.hack
- src/Validation/Rules/KnownTypeNamesRule.hack
- src/Validation/Validator.hack
- src/__Private/Visitor/ASTVisitor.hack
- tests/ErrorTest.hack
- tests/Validation/KnownTypeNamesRuleTest.hack
Port [KnownTypeNamesRule](https://github.com/graphql/graphql-js/blob/main/src/validation/rules/KnownTypeNamesRule.js).
We don't handle SDL validation because we'd like to that separately during codegen.
> Port KnownTypeNamesRule

- src/BaseSchema.hack
- src/Codegen/Builders/InterfaceBuilder.hack
- src/Codegen/Generator.hack
- src/ExecutionContext.hack
- src/FieldCollector.hack
- src/FieldDefinition.hack
- src/Graphpinator/Parser/Field/SelectionSet.hack
- src/Resolver.hack
- src/Types/InputOutput/LeafType.hack
- src/Types/Output/ListOutputType.hack
- src/Types/Output/NullableOutputType.hack
- src/Types/Output/ObjectType.hack
- src/Types/Output/OutputType.hack
- tests/FragmentTest.hack
- tests/gen/IIntrospectionInterfaceA.hack
- tests/gen/IIntrospectionInterfaceB.hack
- tests/gen/IIntrospectionInterfaceC.hack
- tests/gen/InterfaceA.hack
- tests/gen/InterfaceB.hack
- tests/gen/Schema.hack
- tests/gen/User.hack
This makes it possible to execute queries with fragments, including all the fun cases around nested fragments and nested overlapping selection sets (see new test case).
One missing part is correctly codegenning the `INTERACES` const on object types (similarly to `POSSIBLE_TYPES` on interfaces) -- I assumed @mwildehahn is probably working on that already so for now I just hardcoded the value that makes the test pass :)
> implement field collection (aka defragmentation)

- src/Codegen/Builders/CompositeBuilder.hack
- src/Codegen/Builders/Fields/ConnectionFieldBuilder.hack
- src/Codegen/Builders/Fields/FieldBuilder.hack
- src/Codegen/Builders/Fields/IFieldBuilder.hack
- src/Codegen/Builders/Fields/MethodFieldBuilder.hack
- src/Codegen/Builders/Fields/ShapeFieldBuilder.hack
- src/Codegen/Builders/Fields/StaticFieldBuilder.hack
- src/Codegen/Builders/InterfaceBuilder.hack
- src/Codegen/Builders/ObjectBuilder.hack
- src/Codegen/FieldResolver.hack
- src/Codegen/Generator.hack
- src/Codegen/MultiParser.hack
- src/Codegen/Types.hack
- src/Pagination/Connection.hack
- src/Pagination/Edge.hack
- src/Pagination/PageInfo.hack
- src/playground/Playground.hack
- src/playground/UserConnection.hack
- tests/PaginationTest.hack
- tests/gen/Human.hack
- tests/gen/PageInfo.hack
- tests/gen/Schema.hack
- tests/gen/UserConnection.hack
- tests/gen/UserEdge.hack
This is a pretty gnarly (IMO) first stab at pagination. You'll notice that I changed _a lot_ of things, especially when it comes to codegen. That's because connections and edges accept type parameters, which we've not handled yet during codegen. And to be honest, I wasn't sure _how_ to handle type parameters, so instead I just special-cased the connection and edge objects. What this means practically is that I've decoupled code generation from reflection. I _think_ this is a good thing. Basically, we no longer need reflection methods and classes to generate code — we can use them if we have them in hand, and we usually do, but for the case of generating classes which subclass classes with type arguments, or generating methods which return generics, it's better to just explicitly tell the …
> Pagination

- src/Codegen/Builders/InputObjectBuilder.hack
- src/Types/Input/InputObjectType.hack
- src/Types/Input/NamedInputType.hack
- src/Types/InputOutput/LeafType.hack
- tests/gen/CreateTeamInput.hack
- tests/gen/CreateUserInput.hack
Needs proper implementation, since they can have list fields which aren't `<<__Enforceable>>`.
I updated the codegen code to minimize duplicate logic, since the generated class now has 3 similar methods.
> fix InputObjectType::assertValidVariableValues

- src/Codegen/Builders/EnumBuilder.hack
- src/Codegen/Builders/InputObjectBuilder.hack
- src/Codegen/Types.hack
- src/Introspection/__EnumValue.hack
- src/Introspection/__InputValue.hack
- src/Introspection/__Type.hack
- src/Types/Input/InputObjectType.hack
- src/Types/InputOutput/EnumType.hack
- src/Types/NonNullableType.hack
- src/playground/IntrospectionTestObjects.hack
- tests/IntrospectionTest.hack
- tests/gen/CreateTeamInput.hack
- tests/gen/CreateUserInput.hack
- tests/gen/IntrospectionEnum.hack
- tests/gen/IntrospectionNestedInput.hack
- tests/gen/IntrospectionRootInput.hack
- tests/gen/Schema.hack
- tests/gen/__EnumValue.hack
- tests/gen/__InputValue.hack
- tests/gen/__Type.hack
- tests/gen/__TypeKind.hack
This implements `enumValues` and `inputFields` which were the two big remaining introspection pieces remaining. There are still some TODOs scattered to support description, default value, etc.
I broke this up into two commits, first for enum values and next for input fields.
For input objects, we currently have a bug where you can't use a value with a generic parameter, ie this doesn't work: 
```
<<GraphQL\InputObjectType('IntrospectionRootInput', '')>>
type TRootInput = shape(
'scalar' => string,
'nested' => TNestedInput,
'vec_of_nested' => vec<TNestedInput>,
);
<<GraphQL\InputObjectType('IntrospectionNestedInput', '')>>
type TNestedInput = shape(
'string' => string,
'vec_of_string' => vec<string>,
);
```
Because `THackType` is marked as `__Enforceable` so we can't use it with generics …
> Remaining introspection methods

- src/Resolver.hack
- src/UserFacingError.hack
- tests/ErrorTest.hack
- tests/PlaygroundTest.hack
Adds a new option to the resolver, `verbose_errors`. When enabled, we also surface the cause of each `FieldResolverError`.
> Support verbose field resolver errors

- src/BaseSchema.hack
- src/Codegen/Generator.hack
- src/Resolver.hack
- src/Types/Input/InputType.hack
- src/Validation/Rules/KnownTypeNamesRule.hack
- src/Validation/ValidationContext.hack
- src/Validation/Validator.hack
- src/__Private/Visitor/TypeInfo.hack
- tests/PlaygroundTest.hack
- tests/Validation/BaseValidationTest.hack
- tests/gen/Schema.hack
This is a small refactor I've been wanting to get in for awhile. We should always pass around an instance of `BaseSchema` instead of `classname<BaseSchema>`, for consistency's sake.
> Always use schema instance

- src/Codegen/Builders/ObjectBuilder.hack
- src/Codegen/Types.hack
- tests/BasicTest.hack
- tests/Fixtures/NamespaceTestObjects.hack
- tests/Fixtures/Playground.hack
- tests/PaginationTest.hack
- tests/gen/Baz.hack
- tests/gen/FooConnection.hack
- tests/gen/FooObjectEdge.hack
- tests/gen/Query.hack
- tests/gen/Schema.hack
- tests/schema.json
We were generating bad code for namespaced connections. I fixed this by:
1. Removing the namespace for any resolver we pass into a field definition (i.e., any resolver generated by `output_type` that isn't a primitive resolver).
2. Removing the namespace when generating the name for the GraphQL connection.
This means that connections with the same name in different namespaces can collide. Eventually we could fix this by:
1. Merging the namespace name with the connection name.
2. Allowing user-provided connection names which differ from the Hack class name.
Neither solution seems necessary as of yet.
I also added a test asserting we handle namespaced return types correctly, which we do.
> Better handling for namespaced objects

- src/Codegen/Generator.hack
We should drive connection codegen off whether the class subclasses connection, not based off the name.
> Fix connection codegen

- src/Codegen/Generator.hack
- tests/Fixtures/Playground.hack
I have a class with a non-graphql attribute class (`<<__ConsistentConstruct>>`) that was being picked up at this line and leading to codegen failures. the code expects my non-graphql class to exist in `$class_fields`, and this PR simply continues if the class has attribute classes but no graphql attribute classes. another solution could be to more narrowly tailor the directories that my codegen script checks, but seems like we should be able to handle this case fairly well.
> Fix bug for classes with non-graphql attribute classes

- src/Pagination/Connection.hack
- tests/PaginationTest.hack
Fix a minor bug where hasPreviousPage would return null, instead of false
> Fix a minor bug where hasPrevious/NextPage returns null

- src/Pagination/Connection.hack
- src/Pagination/ListConnection.hack
- tests/Fixtures/UserConnection.hack
- tests/PaginationTest.hack
When retrieving a list of items the project will grab 1 extra to cleverly figure out if there is a next page. However the project always assumes the list is sort ascending, when sending a descending list it doesn't remove the extra item but the item at the other end of the list.
To avoid adding sort direction to the project I removed the cleverness, and instead just fetch a single item of the next page to see if there is more
I also renamed
hasPageBeforeAfterCursor > hasNextPage
hasPageAfterBeforeCursor > hasPreviousPage
because I thought they were more clear
> Sort desc bug

- src/Pagination/Connection.hack
passes more params to hasNextPage/hasPreviousPage which allows for more complex overriding. This is especally necessary when using SQL with graphql. As you have to artificially change the sort order in SQL to retrieve things, thus changing which start or end cursor to use for the next/prev page
> Page cursor

- src/Request.hack
- src/Resolver.hack
- src/Response.hack
- src/Validation/Validator.hack
- tests/ErrorTest.hack
- tests/FixtureTest.hack
- tests/Validation/BaseValidationTest.hack
Per discussion with @sarahhenkens, we want to create a convenient way to access the operation name for each GraphQL request (and other useful metadata, eventually). As such, we decided it would be convenient to create request/response interfaces exposing this information. So, instead of the following:
```hack
return await $resolver->resolve($input, $variables);
```
We would now do:
```hack
$request = GraphQL\Request::build($input, $variables);
$response = await $resolver->resolve($request);
return $response->toShape();
```
It's a bit more verbose, but somewhat more flexible, since we can now do things like `$request->getOperationName()` to retrieve the name of the operation which will be executed (if any).
We could provide a simpler interface:
```hack
$response = await …
```
> Add request/response interfaces
